language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
before_install:
  - cd docker/dev
  - docker-compose up
  - docker ps -a
before_script:
  - cd ../../src/
script:
  - mvn clean test -Ptest-business